-- The modeler tables as an installation has them before folders exist, so the migration below is
-- exercised against the shape it will actually meet.

CREATE TABLE IF NOT EXISTS MOD_PROCESSES_DIAGRAMS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    NAME VARCHAR(255),
    PROCESSKEY VARCHAR(100) UNIQUE,
    DESCRIPTION VARCHAR(150),
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    ACTIVE BOOLEAN DEFAULT TRUE,
    TYPE VARCHAR(50),
    VERSION INTEGER DEFAULT 1,
    DIAGRAM BLOB
);

CREATE TABLE IF NOT EXISTS MOD_FORMS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(150),
    CREATED TIMESTAMP,
    UPDATED TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    FORM_SCHEMA BLOB NOT NULL,
    FORMID VARCHAR(100) UNIQUE NOT NULL,
    VERSION INTEGER DEFAULT 1
);

MERGE INTO MOD_PROCESSES_DIAGRAMS (ID, NAME, PROCESSKEY, TYPE, VERSION, DIAGRAM) KEY(ID)
    VALUES ('diagram-1', 'Invoice', 'invoice', 'bpmn-c7', 1, NULL);
MERGE INTO MOD_PROCESSES_DIAGRAMS (ID, NAME, PROCESSKEY, TYPE, VERSION, DIAGRAM) KEY(ID)
    VALUES ('diagram-2', 'Order', 'order', 'bpmn-c7', 1, NULL);
MERGE INTO MOD_FORMS (ID, FORMID, FORM_SCHEMA, VERSION) KEY(ID) VALUES ('form-1', 'invoice-form', RAWTOHEX('{}'), 1);

-- The diagram entity reaches its usages, so the tables they live in have to be here as well
CREATE TABLE IF NOT EXISTS MOD_USER_SESSIONS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(100),
    STARTED_AT TIMESTAMP,
    ENDED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MOD_DIAGRAM_USAGE (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    DIAGRAM_ID VARCHAR(36) NOT NULL,
    SESSION_ID VARCHAR(36) NOT NULL,
    OPENED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CLOSED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MOD_FORM_USAGE (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    FORM_ID VARCHAR(36) NOT NULL,
    SESSION_ID VARCHAR(36) NOT NULL,
    OPENED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CLOSED_AT TIMESTAMP
);
