-- Folders for the modeler, and the move of a flat installation into one.
--
-- The id of the folder this creates is fixed on purpose: the statements then need no UUID
-- function, which every database spells differently, and an installation can be recognised.

CREATE TABLE IF NOT EXISTS MOD_FOLDERS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    PARENT_ID VARCHAR(36),
    NAME VARCHAR(255) NOT NULL,
    CREATED TIMESTAMP,
    CREATED_BY VARCHAR(100),
    UPDATED TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    CONSTRAINT UK_MOD_FOLDERS_PARENT_NAME UNIQUE (PARENT_ID, NAME),
    CONSTRAINT FK_MOD_FOLDERS_PARENT FOREIGN KEY (PARENT_ID) REFERENCES MOD_FOLDERS (ID)
);

CREATE INDEX IF NOT EXISTS IDX_MOD_FOLDERS_PARENT ON MOD_FOLDERS (PARENT_ID);

ALTER TABLE MOD_PROCESSES_DIAGRAMS ADD COLUMN IF NOT EXISTS FOLDER_ID VARCHAR(36);
ALTER TABLE MOD_FORMS ADD COLUMN IF NOT EXISTS FOLDER_ID VARCHAR(36);

-- The folder today's models are put in
MERGE INTO MOD_FOLDERS (ID, PARENT_ID, NAME, CREATED) KEY(ID)
    VALUES ('00000000-0000-0000-0000-0000000000d1', NULL, 'General', CURRENT_TIMESTAMP);

UPDATE MOD_PROCESSES_DIAGRAMS SET FOLDER_ID = '00000000-0000-0000-0000-0000000000d1' WHERE FOLDER_ID IS NULL;
UPDATE MOD_FORMS SET FOLDER_ID = '00000000-0000-0000-0000-0000000000d1' WHERE FOLDER_ID IS NULL;
