#!/bin/bash
#
# Bump npm dev prerelease version (e.g. 1.0.3-dev.7 → 1.0.3-dev.8)
#
# Usage:
#   ./npm-bump-dev.sh                    # bumps frontend (default)
#   ./npm-bump-dev.sh bpm-sdk            # bumps bpm-sdk
#   ./npm-bump-dev.sh --pr               # bumps frontend and creates PR
#   ./npm-bump-dev.sh bpm-sdk --pr       # bumps bpm-sdk and creates PR
#   ./npm-bump-dev.sh --pr frontend      # same as above (order independent)
#
set -e

# Parse arguments
create_pr=false
package=""

for arg in "$@"; do
  if [ "$arg" = "--pr" ]; then
    create_pr=true
  else
    package="$arg"
  fi
done

package="${package:-frontend}"

# Echo header
echo "=========================================="
echo "npm-bump-dev.sh"
echo "=========================================="
echo "Package: $package"
echo "Create PR: $create_pr"
echo ""

root="$(cd "$(dirname "$0")" && pwd)"
pkg_json="$root/$package/package.json"

if [ ! -f "$pkg_json" ]; then
  echo "Error: $pkg_json not found"
  exit 1
fi

# Prerequisites for PR creation
if [ "$create_pr" = true ]; then
  echo "Checking prerequisites for PR creation..."

  # Check working directory
  if ! git diff-index --quiet HEAD --; then
    echo "Error: Working directory has uncommitted changes"
    echo "Commit or stash changes before running with --pr"
    exit 1
  fi
  echo "✓ Working directory is clean"
  echo ""
fi

cd "$root/$package"

# Capture old version
old_version=$(node -p "require('./package.json').version")
echo "Current version: $old_version"
echo ""

# Bump version
echo "Bumping version..."
npm version prerelease --preid=dev --no-git-tag-version
new_version=$(node -p "require('./package.json').version")
echo "✓ Version bumped to: $new_version"
echo ""

if [ "$create_pr" = true ]; then
  echo "=========================================="
  echo "Creating branch and PR"
  echo "=========================================="

  # Save current branch to return to it later
  original_branch=$(git branch --show-current)

  branch_name="bump/dev-$package-$new_version"
  echo "Branch name: $branch_name"
  echo ""

  # Create and switch to new branch
  echo "Creating new branch..."
  git checkout -b "$branch_name"
  echo "✓ Branch created: $branch_name"
  echo ""

  # Git operations on new branch
  echo "Staging changes..."
  git add package.json
  echo "✓ Added package.json"

  # Also add package-lock.json if it exists and is tracked
  if [ -f package-lock.json ] && git ls-files --error-unmatch package-lock.json &> /dev/null; then
    git add package-lock.json
    echo "✓ Added package-lock.json"
  fi
  echo ""

  commit_message="bump: increase $package version to $new_version"
  echo "Creating commit..."
  git commit -m "$commit_message"
  echo "✓ Commit created: $commit_message"
  echo ""

  # Push to remote
  echo "Pushing to remote..."
  git push -u origin "$branch_name"
  echo "✓ Pushed to origin/$branch_name"
  echo ""

  # Create PR if gh is available
  if command -v gh &> /dev/null; then
    echo "Creating pull request..."
    pr_title="bump: increase $package version to $new_version"
    pr_body="## Summary
Automated version bump for $package from $old_version to $new_version.

This is a prerelease development version increment.

## Changes
- Bump $package version to $new_version

🤖 Generated by npm-bump-dev.sh"

    pr_url=$(gh pr create --title "$pr_title" --body "$pr_body" --base main)
    echo "✓ PR created successfully"
    echo ""
    echo "PR URL: $pr_url"
    echo ""
  else
    echo "⚠ GitHub CLI (gh) not found - skipping PR creation"
    echo "You can create a PR manually at: https://github.com/your-repo/compare/$branch_name"
    echo ""
  fi

  # Switch back to original branch
  git checkout "$original_branch"
else
  # Commit on current branch (non-PR mode)
  echo "Staging changes..."
  git add package.json
  echo "✓ Added package.json"

  # Also add package-lock.json if it exists and is tracked
  if [ -f package-lock.json ] && git ls-files --error-unmatch package-lock.json &> /dev/null; then
    git add package-lock.json
    echo "✓ Added package-lock.json"
  fi
  echo ""

  commit_message="bump: increase $package version to $new_version"
  echo "Creating commit..."
  git commit -m "$commit_message"
  echo "✓ Commit created: $commit_message"
  echo ""
fi

# Final summary
echo "=========================================="
echo "Summary"
echo "=========================================="
echo "Package: $package"
echo "Version: $old_version → $new_version"
if [ "$create_pr" = true ]; then
  echo "Branch: $branch_name"
  if [ -n "$pr_url" ]; then
    echo "PR: $pr_url"
  else
    echo "PR: Not created (install GitHub CLI or create manually)"
    echo "    https://github.com/cibseven/cibseven-webclient/compare/$branch_name"
  fi
fi
echo ""
echo "Done! ✓"
